#!/bin/bash
#
# Main program to generate the Github's contributions board work

SCRIPT_DIR=$( dirname "$( readlink --canonicalize "$0" )" )

. "${SCRIPT_DIR}/lib/general.sh"
. "${SCRIPT_DIR}/lib/validation.sh"
. "${SCRIPT_DIR}/lib/work.sh"

general::init_variables

general::parse_inputs "$@"
general::validate_inputs

work::define_multiplier
work::init_work
work::commit_work

exit 0
